
package TrainTicket;
import java.io.PrintStream;
import java.net.Socket;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Random;



public class TrainTickets extends javax.swing.JFrame {

    
    public TrainTickets() {
        
     /*   try{
            Socket sock = new Socket("localhost",9999);
            
            InputStreamReader rd = new InputStreamReader(System.in);
            BufferedReader ed = new BufferedReader(rd);
        }
        catch(Exception ex)
        {
            
        }
     */
        
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        radioStandard = new javax.swing.JRadioButton();
        radioEconomy = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        radioSingle = new javax.swing.JRadioButton();
        radioReturn = new javax.swing.JRadioButton();
        radioAdultYes = new javax.swing.JRadioButton();
        radioChildYes = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        ComboBox = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        SubtotalDisplay = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        TaxDisplay = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        TotalDisplay = new javax.swing.JLabel();
        TotalButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        ClassDisplay = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        TicketTypeDisplay = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        AdultDisplay = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        ChildDisplay = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        FromDisplay = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        ToDisplay = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        DateDisplay = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        TimeDisplay = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        RouteDisplay = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        TicketNoDisplay = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        PriceDisplay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 70)); // NOI18N
        jLabel1.setText("Train Ticketing System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));

        radioStandard.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        radioStandard.setText("Standard");
        radioStandard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioStandardActionPerformed(evt);
            }
        });

        radioEconomy.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        radioEconomy.setText("Economy");
        radioEconomy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEconomyActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Class");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("Ticket Type");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("Adult");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("Child");

        radioSingle.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        radioSingle.setText("Single");

        radioReturn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        radioReturn.setText("Return");

        radioAdultYes.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        radioAdultYes.setText("Yes");
        radioAdultYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAdultYesActionPerformed(evt);
            }
        });

        radioChildYes.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        radioChildYes.setText("Yes");
        radioChildYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioChildYesActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setText("Destination :");

        ComboBox.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Colombo", "Kandy", "Anuradhapura" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(radioStandard)
                    .addComponent(radioEconomy)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(radioSingle)
                                .addGap(65, 65, 65)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioAdultYes)
                            .addComponent(jLabel4))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioChildYes)
                            .addComponent(jLabel5)))
                    .addComponent(radioReturn)
                    .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioStandard, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioSingle)
                    .addComponent(radioAdultYes)
                    .addComponent(radioChildYes))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioEconomy)
                    .addComponent(radioReturn))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Subtotal :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Tax :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Total :");

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        SubtotalDisplay.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SubtotalDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SubtotalDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        TaxDisplay.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TaxDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TaxDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        TotalDisplay.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TotalDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TotalDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        TotalButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        TotalButton.setText("TOTAL");
        TotalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TotalButtonMouseClicked(evt);
            }
        });
        TotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalButtonActionPerformed(evt);
            }
        });

        ResetButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        ResetButton.setText("RESET");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        ExitButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        ExitButton.setText("EXIT");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(TotalButton)
                .addGap(60, 60, 60)
                .addComponent(ResetButton)
                .addGap(80, 80, 80)
                .addComponent(ExitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalButton)
                    .addComponent(ResetButton)
                    .addComponent(ExitButton))
                .addGap(24, 24, 24))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setText("Class");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setText("Ticket Type");

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        ClassDisplay.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ClassDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ClassDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        TicketTypeDisplay.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TicketTypeDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TicketTypeDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel12.setText("Adult");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel13.setText("Child");

        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        AdultDisplay.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdultDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdultDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        ChildDisplay.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ChildDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ChildDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel14.setText("From :");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel15.setText("To :");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel16.setText("Date :");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel17.setText("Time :");

        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        FromDisplay.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FromDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FromDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        ToDisplay.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ToDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ToDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        DateDisplay.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DateDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DateDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel20.setText("Route :");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel18.setText("Ticket No :");

        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        TimeDisplay.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TimeDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TimeDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        RouteDisplay.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RouteDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RouteDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        TicketNoDisplay.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(TicketNoDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TicketNoDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel19.setText("Price");

        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 3));

        PriceDisplay.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PriceDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addComponent(PriceDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel10)
                                .addGap(117, 117, 117)
                                .addComponent(jLabel11))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addGap(18, 18, 18)
                                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addGap(18, 18, 18)
                                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel17))
                                    .addGap(26, 26, 26)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(217, 217, 217))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(147, 147, 147))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19)
                            .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(504, 504, 504))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioEconomyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEconomyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioEconomyActionPerformed

    private void radioStandardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioStandardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioStandardActionPerformed

    private void radioAdultYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAdultYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioAdultYesActionPerformed

    private void radioChildYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioChildYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioChildYesActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        SubtotalDisplay.setText(null);
        TaxDisplay.setText(null);
        TotalDisplay.setText(null);
        ClassDisplay.setText(null);
        TicketTypeDisplay.setText(null);
        ChildDisplay.setText(null);
        AdultDisplay.setText(null);
        PriceDisplay.setText(null);
        FromDisplay.setText(null);
        ToDisplay.setText(null);
        DateDisplay.setText(null);
        TimeDisplay.setText(null);
        RouteDisplay.setText(null);
        TicketNoDisplay.setText(null);       
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.getContentPane().setBackground(Color.red);
    }//GEN-LAST:event_formWindowActivated

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void TotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalButtonActionPerformed

/*=========================Setting Time at instance===========================*/
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH.mm.ss");
        TimeDisplay.setText(tTime.format(timer.getTime()));
        
/*=========================Setting Date at instance===========================*/
        SimpleDateFormat tDate = new SimpleDateFormat("dd.mm.yyyy");
        DateDisplay.setText(tDate.format(timer.getTime()));
        
        FromDisplay.setText("Colombo  *");
        ToDisplay.setText((String) ComboBox.getSelectedItem()+ " *");
        
/*=========================Random Number Generator=============*/
        
        int num1;
        String q1 = "";
        num1 = 1325 + (int) (Math.random()*4238);
        q1 += num1 + 1325;
        TicketNoDisplay.setText(q1);
        
        RouteDisplay.setText("ANY");
    }//GEN-LAST:event_TotalButtonActionPerformed

    private void TotalButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotalButtonMouseClicked
        double tax = 19.50;
        double MilesK8 = 180.23;
        double MilesK12 = 250.10;
        
        double totalCost, economy = 3.85, firstClass = 5.60;
   
/*=======================Done For Standard Travel (Kandy)======================*/   
        
        if((radioStandard.isSelected()) && (radioSingle.isSelected()) && (radioAdultYes.isSelected()) 
                && ComboBox.getSelectedItem().equals("Kandy"))
        
            {
                totalCost    = (tax * MilesK8) /100;
                String sTax  = String.format ("Rs % .2f",totalCost);
                TaxDisplay.setText(sTax);
                String subTotal = String.format("Rs% .2f",MilesK8);
                SubtotalDisplay.setText(subTotal);
                String Total =String.format("Rs% .2f",MilesK8 +totalCost);
                TotalDisplay.setText(Total);
                PriceDisplay.setText(Total);
                ClassDisplay.setText("STANDARD");
                TicketTypeDisplay.setText("ONE WAY");
                AdultDisplay.setText("ONE");
                ChildDisplay.setText("NIL");
            }
        
        else if((radioStandard.isSelected()) && (radioReturn.isSelected()) && (radioAdultYes.isSelected()) 
                && ComboBox.getSelectedItem().equals("Kandy"))
                  
            {
                totalCost    = (tax * MilesK8 * 2) /100;
                String sTax  = String.format ("Rs % .2f",totalCost);
                TaxDisplay.setText(sTax);
                String subTotal = String.format("Rs% .2f",MilesK8 * 2);
                SubtotalDisplay.setText(subTotal);
                String Total =String.format("Rs% .2f",(MilesK8 +totalCost) * 2);
                TotalDisplay.setText(Total);
                PriceDisplay.setText(Total);
                ClassDisplay.setText("STANDARD");
                TicketTypeDisplay.setText("RETURN");
                AdultDisplay.setText("ONE");
                ChildDisplay.setText("NIL");
            }
            
         else if((radioStandard.isSelected( )) && (radioSingle.isSelected()) && (radioChildYes.isSelected ()) 
                 && ComboBox.getSelectedItem().equals("Kandy"))
                  
            {
                totalCost    = (tax * MilesK8) /100;
                String sTax  = String.format ("Rs % .2f",totalCost -18);
                TaxDisplay.setText(sTax);
                String subTotal = String.format("Rs% .2f",MilesK8);
                SubtotalDisplay.setText(subTotal);
                TotalDisplay.setText(subTotal);
                String Total =String.format("Rs% .2f",MilesK8 +totalCost -18);
                TotalDisplay.setText(Total);
                PriceDisplay.setText(Total);
                ClassDisplay.setText("STANDARD");
                TicketTypeDisplay.setText("ONE WAY");
                AdultDisplay.setText("NIL");
                ChildDisplay.setText("ONE");
                      
             }
      
         else if((radioStandard.isSelected( )) && (radioReturn.isSelected()) && (radioChildYes.isSelected ()) 
                 && ComboBox.getSelectedItem().equals("Kandy"))
                  
            {
                totalCost    = (tax * MilesK8 * 2) /100;
                String sTax  = String.format ("Rs % .2f",totalCost -18);
                TaxDisplay.setText(sTax);
                String subTotal = String.format("Rs% .2f",MilesK8 * 2);
                SubtotalDisplay.setText(subTotal);
                TotalDisplay.setText(subTotal);
                String Total =String.format("Rs% .2f",((MilesK8 +totalCost) * 2)-18);
                TotalDisplay.setText(Total);
                PriceDisplay.setText(Total);
                ClassDisplay.setText("STANDARD");
                TicketTypeDisplay.setText("RETURN");
                AdultDisplay.setText("NIL");
                ChildDisplay.setText("ONE");
                      
             }
      
        /*=======================Done For Economy Travel (Kandy)======================*/   
        
        if((radioEconomy.isSelected()) && (radioSingle.isSelected()) && (radioAdultYes.isSelected()) 
                && ComboBox.getSelectedItem().equals("Kandy"))
        
            {
                totalCost    = (tax * (MilesK8 + economy)) /100;
                String sTax  = String.format ("Rs % .2f",totalCost);
                TaxDisplay.setText(sTax);
                String subTotal = String.format("Rs% .2f",MilesK8 + economy);
                SubtotalDisplay.setText(subTotal);
                String Total =String.format("Rs% .2f",MilesK8 + economy +totalCost);
                TotalDisplay.setText(Total);
                PriceDisplay.setText(Total);
                ClassDisplay.setText("ECONOMY");
                TicketTypeDisplay.setText("ONE WAY");
                AdultDisplay.setText("ONE");
                ChildDisplay.setText("NIL");
            }
        
        else if((radioEconomy.isSelected()) && (radioReturn.isSelected()) && (radioAdultYes.isSelected()) 
                && ComboBox.getSelectedItem().equals("Kandy"))
                  
            {
                totalCost    = ((tax * (MilesK8 + economy)) * 2) /100;
                String sTax  = String.format ("Rs % .2f",totalCost);
                TaxDisplay.setText(sTax);
                String subTotal = String.format("Rs% .2f",(MilesK8 + economy)* 2);
                SubtotalDisplay.setText(subTotal);
                String Total =String.format("Rs% .2f",(MilesK8 + economy +totalCost) * 2);
                TotalDisplay.setText(Total);
                PriceDisplay.setText(Total);
                ClassDisplay.setText("ECONOMY");
                TicketTypeDisplay.setText("RETURN");
                AdultDisplay.setText("ONE");
                ChildDisplay.setText("NIL");
            }
            
         else if((radioEconomy.isSelected( )) && (radioSingle.isSelected()) && (radioChildYes.isSelected ()) 
                 && ComboBox.getSelectedItem().equals("Kandy"))
                  
            {
                totalCost    = (tax * (MilesK8 + economy)) /100;
                String sTax  = String.format ("Rs % .2f",totalCost -18);
                TaxDisplay.setText(sTax);
                String subTotal = String.format("Rs% .2f",MilesK8 + economy);
                SubtotalDisplay.setText(subTotal);
                TotalDisplay.setText(subTotal);
                String Total =String.format("Rs% .2f",MilesK8 +totalCost + economy -18);
                TotalDisplay.setText(Total);
                PriceDisplay.setText(Total);
                ClassDisplay.setText("ECONOMY");
                TicketTypeDisplay.setText("ONE WAY");
                AdultDisplay.setText("NIL");
                ChildDisplay.setText("ONE");
                      
             }
      
         else if((radioStandard.isSelected( )) && (radioReturn.isSelected()) && (radioChildYes.isSelected ()) 
                 && ComboBox.getSelectedItem().equals("Kandy"))
                  
            {
                totalCost    = ((tax * (MilesK8 + economy)) * 2) /100;
                String sTax  = String.format ("Rs % .2f",totalCost -18);
                TaxDisplay.setText(sTax);
                String subTotal = String.format("Rs% .2f",(MilesK8 + economy) * 2);
                SubtotalDisplay.setText(subTotal);
                TotalDisplay.setText(subTotal);
                String Total =String.format("Rs% .2f",((MilesK8 +totalCost + economy) * 2)-18);
                TotalDisplay.setText(Total);
                PriceDisplay.setText(Total);
                ClassDisplay.setText("STANDARD");
                TicketTypeDisplay.setText("RETURN");
                AdultDisplay.setText("NIL");
                ChildDisplay.setText("ONE");
                      
             }
        
        /*=======================Done For Standard Travel (Anuradhapura)======================*/   
        
        if((radioStandard.isSelected()) && (radioSingle.isSelected()) && (radioAdultYes.isSelected()) 
                && ComboBox.getSelectedItem().equals("Anuradhapura"))
        
            {
                totalCost    = (tax * MilesK12) /100;
                String sTax  = String.format ("Rs % .2f",totalCost);
                TaxDisplay.setText(sTax);
                String subTotal = String.format("Rs% .2f",MilesK12);
                SubtotalDisplay.setText(subTotal);
                String Total =String.format("Rs% .2f",MilesK12 +totalCost);
                TotalDisplay.setText(Total);
                PriceDisplay.setText(Total);
                ClassDisplay.setText("STANDARD");
                TicketTypeDisplay.setText("ONE WAY");
                AdultDisplay.setText("ONE");
                ChildDisplay.setText("NIL");
            }
        
        else if((radioStandard.isSelected()) && (radioReturn.isSelected()) && (radioAdultYes.isSelected()) 
                && ComboBox.getSelectedItem().equals("Anuradhapura"))
                  
            {
                totalCost    = (tax * MilesK12 * 2) /100;
                String sTax  = String.format ("Rs % .2f",totalCost);
                TaxDisplay.setText(sTax);
                String subTotal = String.format("Rs% .2f",MilesK12 * 2);
                SubtotalDisplay.setText(subTotal);
                String Total =String.format("Rs% .2f",(MilesK12 +totalCost) * 2);
                TotalDisplay.setText(Total);
                PriceDisplay.setText(Total);
                ClassDisplay.setText("STANDARD");
                TicketTypeDisplay.setText("RETURN");
                AdultDisplay.setText("ONE");
                ChildDisplay.setText("NIL");
            }
            
         else if((radioStandard.isSelected( )) && (radioSingle.isSelected()) && (radioChildYes.isSelected ()) 
                 && ComboBox.getSelectedItem().equals("Anuradhapura"))
                  
            {
                totalCost    = (tax * MilesK12) /100;
                String sTax  = String.format ("Rs % .2f",totalCost -18);
                TaxDisplay.setText(sTax);
                String subTotal = String.format("Rs% .2f",MilesK12);
                SubtotalDisplay.setText(subTotal);
                TotalDisplay.setText(subTotal);
                String Total =String.format("Rs% .2f",MilesK12 +totalCost -18);
                TotalDisplay.setText(Total);
                PriceDisplay.setText(Total);
                ClassDisplay.setText("STANDARD");
                TicketTypeDisplay.setText("ONE WAY");
                AdultDisplay.setText("NIL");
                ChildDisplay.setText("ONE");
                      
             }
      
         else if((radioStandard.isSelected( )) && (radioReturn.isSelected()) && (radioChildYes.isSelected ()) 
                 && ComboBox.getSelectedItem().equals("Anuradhapura"))
                  
            {
                totalCost    = (tax * MilesK12 * 2) /100;
                String sTax  = String.format ("Rs % .2f",totalCost -18);
                TaxDisplay.setText(sTax);
                String subTotal = String.format("Rs% .2f",MilesK12 * 2);
                SubtotalDisplay.setText(subTotal);
                TotalDisplay.setText(subTotal);
                String Total =String.format("Rs% .2f",((MilesK12 +totalCost) * 2)-18);
                TotalDisplay.setText(Total);
                PriceDisplay.setText(Total);
                ClassDisplay.setText("STANDARD");
                TicketTypeDisplay.setText("RETURN");
                AdultDisplay.setText("NIL");
                ChildDisplay.setText("ONE");
                      
             }
      
        /*=======================Done For Economy Travel (Colombo)======================*/   
        
        if((radioEconomy.isSelected()) && (radioSingle.isSelected()) && (radioAdultYes.isSelected()) 
                && ComboBox.getSelectedItem().equals("Anuradhapura"))
        
            {
                totalCost    = (tax * (MilesK12 + economy)) /100;
                String sTax  = String.format ("Rs % .2f",totalCost);
                TaxDisplay.setText(sTax);
                String subTotal = String.format("Rs% .2f",MilesK12 + economy);
                SubtotalDisplay.setText(subTotal);
                String Total =String.format("Rs% .2f",MilesK12 + economy +totalCost);
                TotalDisplay.setText(Total);
                PriceDisplay.setText(Total);
                ClassDisplay.setText("ECONOMY");
                TicketTypeDisplay.setText("ONE WAY");
                AdultDisplay.setText("ONE");
                ChildDisplay.setText("NIL");
            }
        
        else if((radioEconomy.isSelected()) && (radioReturn.isSelected()) && (radioAdultYes.isSelected()) 
                && ComboBox.getSelectedItem().equals("Anuradhapura"))
                  
            {
                totalCost    = ((tax * (MilesK12 + economy)) * 2) /100;
                String sTax  = String.format ("Rs % .2f",totalCost);
                TaxDisplay.setText(sTax);
                String subTotal = String.format("Rs% .2f",(MilesK12 + economy)* 2);
                SubtotalDisplay.setText(subTotal);
                String Total =String.format("Rs% .2f",(MilesK12 + economy +totalCost) * 2);
                TotalDisplay.setText(Total);
                PriceDisplay.setText(Total);
                ClassDisplay.setText("ECONOMY");
                TicketTypeDisplay.setText("RETURN");
                AdultDisplay.setText("ONE");
                ChildDisplay.setText("NIL");
            }
            
         else if((radioEconomy.isSelected( )) && (radioSingle.isSelected()) && (radioChildYes.isSelected ()) 
                 && ComboBox.getSelectedItem().equals("Anuradhapura"))
                  
            {
                totalCost    = (tax * (MilesK12 + economy)) /100;
                String sTax  = String.format ("Rs % .2f",totalCost -18);
                TaxDisplay.setText(sTax);
                String subTotal = String.format("Rs% .2f",MilesK12 + economy);
                SubtotalDisplay.setText(subTotal);
                TotalDisplay.setText(subTotal);
                String Total =String.format("Rs% .2f",MilesK12 +totalCost + economy -18);
                TotalDisplay.setText(Total);
                PriceDisplay.setText(Total);
                ClassDisplay.setText("ECONOMY");
                TicketTypeDisplay.setText("ONE WAY");
                AdultDisplay.setText("NIL");
                ChildDisplay.setText("ONE");
                      
             }
      
         else if((radioStandard.isSelected( )) && (radioReturn.isSelected()) && (radioChildYes.isSelected ()) 
                 && ComboBox.getSelectedItem().equals("Anuradhapura"))
                  
            {
                totalCost    = ((tax * (MilesK12 + economy)) * 2) /100;
                String sTax  = String.format ("Rs % .2f",totalCost -18);
                TaxDisplay.setText(sTax);
                String subTotal = String.format("Rs% .2f",(MilesK12 + economy) * 2);
                SubtotalDisplay.setText(subTotal);
                TotalDisplay.setText(subTotal);
                String Total =String.format("Rs% .2f",((MilesK12 +totalCost + economy) * 2)-18);
                TotalDisplay.setText(Total);
                PriceDisplay.setText(Total);
                ClassDisplay.setText("STANDARD");
                TicketTypeDisplay.setText("RETURN");
                AdultDisplay.setText("NIL");
                ChildDisplay.setText("ONE");
                      
             }
    }//GEN-LAST:event_TotalButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainTickets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdultDisplay;
    private javax.swing.JLabel ChildDisplay;
    private javax.swing.JLabel ClassDisplay;
    private javax.swing.JComboBox ComboBox;
    private javax.swing.JLabel DateDisplay;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel FromDisplay;
    private javax.swing.JLabel PriceDisplay;
    private javax.swing.JButton ResetButton;
    private javax.swing.JLabel RouteDisplay;
    private javax.swing.JLabel SubtotalDisplay;
    private javax.swing.JLabel TaxDisplay;
    private javax.swing.JLabel TicketNoDisplay;
    private javax.swing.JLabel TicketTypeDisplay;
    private javax.swing.JLabel TimeDisplay;
    private javax.swing.JLabel ToDisplay;
    private javax.swing.JButton TotalButton;
    private javax.swing.JLabel TotalDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton radioAdultYes;
    private javax.swing.JRadioButton radioChildYes;
    private javax.swing.JRadioButton radioEconomy;
    private javax.swing.JRadioButton radioReturn;
    private javax.swing.JRadioButton radioSingle;
    private javax.swing.JRadioButton radioStandard;
    // End of variables declaration//GEN-END:variables
}
